[phases.setup]
nixPkgs = ['nodejs-18_x']
workDir = 'client'

[phases.install]
cmds = ['cd client && npm install']

[phases.build]
cmds = ['cd client && npm run build']

[start]
cmd = 'cd client && npm run start'
