[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
workDir = 'client'
cmds = ['npm install']

[phases.build]
workDir = 'client'
cmds = ['npm run build']

[start]
workDir = 'client'
cmd = 'npm run start'
